name: error-response-handler
version: v0.0.1

wdir: .
frameworks: none

venvs:
  - venv

databases:
  - name: error-handler-db
    type: postgresql
    user: [DB_USER]
    password: [DB_PASSWORD]
    host: [DB_HOST]
    port: [DB_PORT]


tests:
  - tool: unittest
    discovery: .
    test_dir: tests