name: error-response-handler
version: v0.0.1

git: https://github.com/aaronahmid/error-response-handler
git_ssh: git@github.com/aaronahmid/error-response-handler

wdir: /home/krummitz/projects/error-response-handler

venvs:
  - name: venv
    dir: .
    on_create: true

databases:
  - name: error-handler-db
    type: postgresql
    user: krumitz
    password: '[DB_PASSWORD]'
    host: '[DB_HOST]'
    port: '[DB_PORT]'
    on_create: true


tests:
  - tool: unittest
    discovery: .
    test_dir: tests
    test_dir: tests
